DROP TABLE IF EXISTS Schedule CASCADE;
DROP TABLE IF EXISTS Restriction CASCADE;
DROP TABLE IF EXISTS Lesson_Tool CASCADE;
DROP TABLE IF EXISTS Classroom_Tool CASCADE;
DROP TABLE IF EXISTS Discipline_Lecturer CASCADE;
DROP TABLE IF EXISTS Discipline_Student CASCADE;
DROP TABLE IF EXISTS Lesson_Student CASCADE;
DROP TABLE IF EXISTS Lesson CASCADE;
DROP TABLE IF EXISTS Student CASCADE;
DROP TABLE IF EXISTS Periodtime CASCADE;
DROP TABLE IF EXISTS Daytime CASCADE;
DROP TABLE IF EXISTS Classroom CASCADE;
DROP TABLE IF EXISTS Tool CASCADE;
DROP TABLE IF EXISTS Specialty CASCADE;
DROP TABLE IF EXISTS Discipline CASCADE;
DROP TABLE IF EXISTS Lecturer CASCADE;
DROP TABLE IF EXISTS Room_type CASCADE;
DROP TABLE IF EXISTS Worksheet CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Roles CASCADE;

CREATE TABLE `Roles` (
  `id` int(11) NOT NULL,
  `role` varchar(100) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET = UTF8;

CREATE TABLE `Users` (
  `id` int(11) AUTO_INCREMENT NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(256) NOT NULL,
  `roleId` int(11) NOT NULL,
  UNIQUE (email),
  PRIMARY KEY (id),
  FOREIGN KEY (roleId) REFERENCES Roles(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=InnoDB CHARACTER SET = UTF8;

CREATE TABLE IF NOT EXISTS Worksheet (
id INT(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(255) NOT NULL,
userId INT(11) NOT NULL,
FOREIGN KEY (userId) REFERENCES Users(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Room_type (
id INT(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Lecturer (
id INT(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(255) NOT NULL,
id_worksheet INT(11) NOT NULL,
FOREIGN KEY (id_worksheet) REFERENCES Worksheet(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Discipline (
id INT(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(255) NOT NULL,
id_worksheet INT(11) NOT NULL,
FOREIGN KEY (id_worksheet) REFERENCES Worksheet(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Specialty (
id INT(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(255) NOT NULL,
id_worksheet INT(11) NOT NULL,
FOREIGN KEY (id_worksheet) REFERENCES Worksheet(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Tool (
id INT(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Classroom (
id INT(11) AUTO_INCREMENT NOT NULL,
building VARCHAR(255) NOT NULL,
number VARCHAR(255) NOT NULL,
capacity INT(11) NOT NULL,
id_room_type INT(11) NOT NULL,
id_worksheet INT(11) NOT NULL,
FOREIGN KEY (id_worksheet) REFERENCES Worksheet(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_room_type) REFERENCES Room_type(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Daytime (
id INT(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Periodtime (
id INT(11) AUTO_INCREMENT NOT NULL,
number INT(11) NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Student (
id INT(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(255) NOT NULL,
course INT(11) NOT NULL,
id_specialty INT(11) NOT NULL,
UNIQUE (name),
FOREIGN KEY (id_specialty) REFERENCES Specialty(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Lesson (
id INT(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(255) NOT NULL,
id_worksheet INT(11) NOT NULL,
id_room_type INT(11) NOT NULL,
id_discipline INT(11) NOT NULL,
id_lecturer INT(11) NOT NULL,
FOREIGN KEY (id_worksheet) REFERENCES Worksheet(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_room_type) REFERENCES Room_type(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
FOREIGN KEY (id_discipline) REFERENCES Discipline(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_lecturer) REFERENCES Lecturer(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Lesson_Student (
id_lesson INT(11) NOT NULL,
id_student INT(11) NOT NULL,
FOREIGN KEY (id_lesson) REFERENCES Lesson(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_student) REFERENCES Student(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
PRIMARY KEY (id_lesson, id_student)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Discipline_Student (
id_discipline INT(11) NOT NULL,
id_student INT(11) NOT NULL,
FOREIGN KEY (id_discipline) REFERENCES Discipline(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_student) REFERENCES Student(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
PRIMARY KEY (id_discipline, id_student)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Discipline_Lecturer (
id_discipline INT(11) NOT NULL,
id_lecturer INT(11) NOT NULL,
FOREIGN KEY (id_discipline) REFERENCES Discipline(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_lecturer) REFERENCES Lecturer(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
PRIMARY KEY (id_discipline, id_lecturer)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Classroom_Tool (
id_classroom INT(11) NOT NULL,
id_tool INT(11) NOT NULL,
FOREIGN KEY (id_classroom) REFERENCES Classroom(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
FOREIGN KEY (id_tool) REFERENCES Tool(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
PRIMARY KEY (id_classroom, id_tool)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Lesson_Tool (
id_lesson INT(11) NOT NULL,
id_tool INT(11) NOT NULL,
selection TINYINT(1),
FOREIGN KEY (id_lesson) REFERENCES Lesson(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_tool) REFERENCES Tool(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
PRIMARY KEY (id_lesson, id_tool)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Restriction (
id INT(11) AUTO_INCREMENT NOT NULL,
id_discipline INT(11),
id_lecturer INT(11),
id_classroom INT(11),
id_daytime INT(11),
id_periodtime INT(11),
selection TINYINT(1) NOT NULL,
id_worksheet INT(11) NOT NULL,
FOREIGN KEY (id_worksheet) REFERENCES Worksheet(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_discipline) REFERENCES Discipline(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_lecturer) REFERENCES Lecturer(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_classroom) REFERENCES Classroom(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_daytime) REFERENCES Daytime(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
FOREIGN KEY (id_periodtime) REFERENCES Periodtime(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS Schedule (
id_lesson INT(11) NOT NULL,
id_classroom INT(11) NOT NULL,
id_daytime INT(11) NOT NULL,
id_periodtime INT(11) NOT NULL,
FOREIGN KEY (id_lesson) REFERENCES Lesson(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_classroom) REFERENCES Classroom(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
FOREIGN KEY (id_daytime) REFERENCES Daytime(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
FOREIGN KEY (id_periodtime) REFERENCES Periodtime(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
PRIMARY KEY (id_lesson, id_classroom, id_daytime, id_periodtime)
) ENGINE=InnoDB CHARACTER SET=UTF8;